# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import problems.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_code', models.CharField(max_length=6, validators=[problems.models.validate_len])),
                ('question', tinymce.models.HTMLField()),
                ('constraints', tinymce.models.HTMLField()),
                ('example', tinymce.models.HTMLField()),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(blank=True, max_length=12000, null=True)),
                ('expected_output', models.TextField(blank=True, max_length=12000, null=True)),
                ('score', models.IntegerField(default=0)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('problem_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problems')),
            ],
            options={
                'ordering': ('problem_code', 'score'),
            },
        ),
        migrations.CreateModel(
            name='topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='problems',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.topics'),
        ),
    ]
