# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import problems.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='best_submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('PRACTICE', 'PRACTICE'), ('CONTEST', 'CONTEST'), ('LAB', 'LAB')], default='PRACTICE', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_code', models.CharField(max_length=6, unique=True, validators=[problems.models.validate_len])),
                ('title', models.CharField(default='title', max_length=100)),
                ('question', tinymce.models.HTMLField()),
                ('constraints', tinymce.models.HTMLField()),
                ('example', tinymce.models.HTMLField()),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.group')),
            ],
            options={
                'ordering': ('group', 'modified'),
            },
        ),
        migrations.CreateModel(
            name='submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120)),
                ('code', models.TextField(blank=True, max_length=12000, null=True)),
                ('score', models.IntegerField(default=0)),
                ('time', models.DecimalField(decimal_places=6, max_digits=8)),
                ('memory', models.DecimalField(decimal_places=1, max_digits=6)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('problem_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problems')),
            ],
        ),
        migrations.CreateModel(
            name='testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(blank=True, max_length=12000, null=True)),
                ('expected_output', models.TextField(blank=True, max_length=12000, null=True)),
                ('score', models.IntegerField(default=0)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('problem_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problems')),
            ],
            options={
                'ordering': ('problem_code', 'score'),
            },
        ),
        migrations.AddField(
            model_name='best_submission',
            name='problem_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problems'),
        ),
        migrations.AddField(
            model_name='best_submission',
            name='submission_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.submission'),
        ),
        migrations.AddField(
            model_name='best_submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user_data'),
        ),
    ]
