# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='topics',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='problems',
            old_name='topic',
            new_name='group',
        ),
    ]
