# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import problems.models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='testcase_submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=10)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='testcase',
            name='time_limit',
            field=models.IntegerField(default=1, validators=[problems.models.validate_timelimit]),
        ),
        migrations.AlterField(
            model_name='best_submission',
            name='problem_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.problems'),
        ),
        migrations.AlterField(
            model_name='best_submission',
            name='submission_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.submission'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='problem_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.problems'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='problem_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.problems'),
        ),
        migrations.AddField(
            model_name='testcase_submission',
            name='submission_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.submission'),
        ),
    ]
