# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20170307_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
