# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20170310_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.group'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='memory',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='testcase_submission',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
