# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20170310_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='open_submissions_to_all',
            field=models.BooleanField(default=False),
        ),
    ]
