# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_auto_20170310_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='best_submission',
            name='user',
            field=models.CharField(max_length=120),
        ),
    ]
