# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_auto_20170308_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='best_submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120)),
                ('code', models.TextField(blank=True, max_length=12000, null=True)),
                ('time', models.DecimalField(decimal_places=6, max_digits=8)),
                ('memory', models.DecimalField(decimal_places=1, max_digits=6)),
                ('score', models.IntegerField(default=0)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('problem_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problems')),
            ],
        ),
        migrations.CreateModel(
            name='submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120)),
                ('code', models.TextField(blank=True, max_length=12000, null=True)),
                ('score', models.IntegerField(default=0)),
                ('time', models.DecimalField(decimal_places=6, max_digits=8)),
                ('memory', models.DecimalField(decimal_places=1, max_digits=6)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('problem_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problems')),
            ],
        ),
    ]
