# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_best_submission_submission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='best_submission',
            options={'ordering': ('modified',)},
        ),
        migrations.AlterModelOptions(
            name='problems',
            options={'ordering': ('group', 'modified')},
        ),
    ]
