# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-14 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys_internal',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.KEYS_List', to_field='key'),
        ),
        migrations.AlterField(
            model_name='keys_list',
            name='key',
            field=models.CharField(max_length=1200, unique=True),
        ),
    ]
