# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('type', models.CharField(default='USER', max_length=100)),
            ],
            options={
                'ordering': ('type',),
            },
        ),
    ]
